import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: '#1a1a1a',
    color: '#e8eaed',
  },
  brandBar: {
    display: 'flex',
    alignItems: 'center',
    height: '36px',
    padding: '0 16px',
    borderBottom: '1px solid #333',
  },
  brandLogo: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    marginRight: '10px',
    objectFit: 'cover',
  },
  brandName: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#e8eaed',
  },
  modeBar: {
    display: 'flex',
    flexDirection: 'row',
    gap: '2px',
    height: '50px',
    padding: '2px 8px',
    alignItems: 'stretch',
    borderBottom: '1px solid #333',
  },
  modeTab: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2px',
    flex: 1,
    padding: '0',
    border: 'none',
    borderRadius: '4px',
    background: 'transparent',
    color: '#999',
    fontSize: '11px',
    cursor: 'pointer',
    textAlign: 'center',
    flexDirection: 'column',
  },
  modeTabActive: {
    background: '#333',
    color: '#e8eaed',
  },
  modeIcon: { fontSize: '16px' },
  modeLabel: {},
  actionBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '36px',
    padding: '0 16px',
    borderBottom: '1px solid #333',
  },
  actionTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#c8a96e',
    flexShrink: 0,
  },
  actionButtons: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  actionButton: {
    border: 'none',
    background: 'transparent',
    color: '#c8a96e',
    fontSize: '12px',
    cursor: 'pointer',
    padding: '2px 0',
    whiteSpace: 'nowrap',
  },
  search: {
    padding: '8px',
    borderBottom: '1px solid #333',
  },
  searchInput: {
    width: '100%',
    height: '32px',
    padding: '0 8px',
    border: '1px solid #444',
    borderRadius: '4px',
    background: '#2a2a2a',
    color: '#e8eaed',
    fontSize: '12px',
    outline: 'none',
  },
  contentList: {
    flex: 1,
    overflow: 'auto',
    padding: '4px 0 120px',
  },
  placeholder: {
    color: '#666',
    fontSize: '12px',
    padding: '16px',
    textAlign: 'center',
  },
  // Folder
  folderItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '5px 8px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
    color: '#e8eaed',
    userSelect: 'none',
  },
  folderToggle: {
    width: '18px',
    fontSize: '18px',
    color: '#999',
    flexShrink: 0,
  },
  folderIcon: {
    fontSize: '14px',
    marginRight: '6px',
    flexShrink: 0,
  },
  folderTitle: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  folderCount: {
    fontSize: '11px',
    color: '#888',
    background: '#2a2a2a',
    borderRadius: '8px',
    padding: '0 6px',
    marginLeft: '6px',
    flexShrink: 0,
  },
  // Note
  noteItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '5px 8px',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#e8eaed',
  },
  noteItemActive: {
    background: '#264f78',
  },
  multiSelected: {
    background: 'rgba(74, 158, 255, 0.15)',
    outline: '1px solid rgba(74, 158, 255, 0.3)',
    outlineOffset: '-1px',
    borderRadius: '4px',
  },
  noteIcon: {
    fontSize: '14px',
    marginRight: '6px',
    flexShrink: 0,
  },
  noteTitle: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  noteDate: {
    fontSize: '11px',
    color: '#666',
    flexShrink: 0,
    marginLeft: '8px',
  },
  renameInput: {
    flex: 1,
    background: '#2a2a2a',
    border: '1px solid #4a9eff',
    borderRadius: '3px',
    color: '#e8eaed',
    fontSize: '13px',
    padding: '2px 6px',
    outline: 'none',
  },
  // Context Menu
  contextMenu: {
    position: 'fixed',
    background: '#2a2a2a',
    border: '1px solid #444',
    borderRadius: '6px',
    padding: '4px 0',
    minWidth: '140px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
    zIndex: 1000,
  },
  contextMenuItem: {
    padding: '6px 12px',
    fontSize: '12px',
    color: '#e8eaed',
    cursor: 'pointer',
  },
  contextMenuSeparator: {
    height: '1px',
    background: '#444',
    margin: '4px 0',
  },
  // Drag & Drop
  dragging: {
    opacity: 0.35,
  },
  dropTarget: {
    background: '#264f78',
    boxShadow: 'inset 3px 0 0 #4a9eff',
    borderRadius: '4px',
  },
  dropTargetRoot: {
    outlineOffset: '-4px',
  },
};
